# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OJILzla7Jr50QxCzdBy0KcccNdfeWCJ
"""

a=100
b=187
print(a==b)

a=56
b=560
print(a!=b)

a=54
b=87
print(a<b)

age=17

if age>=18:
    print("eligible for voting")

mark=76

if mark>=50:
    print("result=pass")
    print("congratulations")
    grade="A"
    print("grade",grade)

age=int(input("enter the age:"))

if age>=18:
    print("you are eligible for voting")
else:
    print("not eligible for voting")