# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3WV9HQtP42WZtxOqVDRYyjAeK6rJDGi
"""

a=66
b=176
print(a>b)and(a!=b)



age=int(input ("enter the age:"))
mark=int(input("enter the mark:"))

if age>=18 and mark>=40:
    print("eligible ")
else:
    print("not eligible")

a=43
b=65
print(a>b) or (a==b)

mark=30
sports_quota=False

if mark>=40 or sports_quota:
    print("eligible ")
else:
    print("not eligible ")

x=45
print(not(x!=9))

is_logged_in=False
if not is_logged_in:
    print("please login first")
else:
    print("welcome back")

