# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VnF63O_v54mTwwHRbr80B-4tPu_EYOW9
"""

import numpy as np
arr=np.array([10,20,30,40])
print(arr)

