# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smSTjnCFJen712XY8gYqclTAzPLuAl-X
"""

import pandas as pd
data={'Name':['Alice','Bob','Charlie'],
      'Age':[25,30,22],
      'City':['Delhi','Mumbai','Chennai']}
df = pd.DataFrame(data)
print(df)

df.index

df.dtypes

df.head()

df.tail()

df.describe()

df.info()

df.values

df.shape

df.size

df.columns