# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rzG5jsYfJlzajHM_hCh2rsCZTMvtwxz
"""

x="eleven"
y="vecna"
villain="""the villain is finally death in last part"""
print(villain)

s="Strangerthings"
print(s[6])
print(s[-10])

s="apple"
print(s[3:])

word="Hello"
print((word + "\n") * 5)

text="the villain is finally death in last part"
print(len(text))

s="i am albert"
print((s+"\n")*10)

text = "Python"

print(text[0])
print(text[1])
print(text[-1])
print(text[-2])

numbers = [10, 20, 30, 40, 50]

print(numbers[0])
print(numbers[2])
print(numbers[-1])