# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14n9kLJ15LIR7Uh1FpS_71VDL6HBYcXZ8
"""

nums=[34,35,36,37,38,39]
nums.insert(0,33)
print(nums)