# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJfdHNeSQvJuEQa51-OiGjbzoHPfyui7
"""

numbers=[11,22,33,44,55]
numbers.append(66)
print(numbers)

numbers=[11,22,33,44,55]
numbers.remove(22)
print(numbers)

numbers=[11,22,33,44,55]
numbers.insert(55,66)
print(numbers)

numbers=[11,22,33,44,55]
numbers.pop()
print(numbers)

numbers=[11,2,3,44,55]
numbers.sort()
print(numbers)

numbers=[11,2,3,44,55]
numbers.reverse()
print(numbers)