# -*- coding: utf-8 -*-
"""List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jnXKazKjwc63Xpe_06LpuO1NV2799sgW
"""

a=[1,2,3,4]
names=["harish","pandi","ram"]
print(type(a))
print(type(names))
print(a)
print(names)

a=list(input("enter the no:"))
print(a)

a=[10,20,30,70,"harish"]
print(a[-3])
print(a[-5])

a=[10,20,30,70,"harish"]
print(a[3])

a=[10,20,30,70,"harish"]
print(a[: :-3])
print(a[: :1])
print(a[:4 :])

a=[10,20,30,70,"harish"]
print(a[:2:-3])

a=[10,20,30,70,"harish"]
b=[10,20,360]
c=[10,20]
print(a+b+c)

a=[10+2,20-45,30,"+"]
print(a)

a=[10,20,30]
print(a*3)
print(len(a))

a=[10,20,30,70,"harish"]
ptint(10

a=[10,20,30]
a.append(40)
print (a)

a=[10,20,30]
a.insert(2,26)
a.insert(3,65)
print(a)

a=[10,20,30,70]
b=[80,62,27]
b.extend(a)
print(b)