# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YDIoZ6WE_pCcnmArRo2EE7Ba9MMoUhbq
"""

a=148
b=194
print(a+b)

a=175
b=194
print(a-b)

a=100
b=0
print(a*b)

a=1000
b=10
print(a/b)

a=1000
b=26
print(a%b)

a=5
b=2
print(a**b)

(cricket,kabadi,football)=(15,26,17)
print(cricket)
print("football")

a=10
b=15
c=45
d=100
e=(a+c*a/b*a-c)
print(e)

name="harish"
print("welcome",name)

mark=int(input("enter the mark"))
if mark>=35:
  print("pass")
else:
  print("fail")

a=10
a+=5
print(a)

a=10
b=18
c=a+b
print(c)

name=input("enter the name:")
for i in range (5):
  print(name)

a=100
b=100
print(a is b)

