# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tKog7MuG0vc-zEi1plvLqwQd9cF8gJM2
"""

import pandas as pd
fruits= pd.Series([100,200,300,400,500],index=['apple','banana','orange','grapes','papaya'])
print(fruits)

print(size)

print(index)

print(values)

print(head(3))

print(tail(3))

print(dtype)

print(fruits.describe())

print(fruits.shape)