# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14n9kLJ15LIR7Uh1FpS_71VDL6HBYcXZ8
"""

nums=[30,40,50,2,3,76,88]
nums.sort()
print(nums)