# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-NE1kf5c-qbTNcSaebMF_mptVGcniem4
"""

print("Apple"=="Apple")

print("xyz">"abc")

s="spiderman brand new day"
print(s.find("s"))

text="stranger things"
print(text.upper())

text="stranger things"
print(text.title())

text="i like python"
print(text.replace("python","java"))
print(text)

text="datascience python"
print(text.split("e"))

name="stranger things"
villain="the villain of vecna"
print(f"the name is {name} and {villain}")

name=" i am albert "
print(name.strip())

name="pirates of the carebian"
print(name[10:15])

text = input("Enter the string: ")
print("Reverse =", text[::-1])